RDKCOM-3154 RDKCMF-8846 Update tvsettings recipes
tvsettings recipes need updating to fix build errors:
tvsettings-hal-noop:
| tvsettings-hal-noop.c:23:20: fatal error: mfrMgr.h: No such file or directory
|  #include mfrMgr.h
|                     ^
| compilation terminated.
tvsettings:
Collected errors:
 * opkg_solver_install: Cannot install package tvsettings.
...
ERROR: rdk-generic-hybrid-wpe-tdk-image-1.0-r0 do_rootfs: Function failed: do_rootfs
tvsettings-plugins:
has dependencies on jsoncpp and boost

Reason for change: RDKCMF-8846 Update tvsettings recipes
Test Procedure: None.
Risks: Low.
Signed-off-by: Stephen Barrett <stephen.barrett@accenture.com>

(cherry picked from commit 134ed813c97c17f16677fdd1902b229194c25fb0)
(cherry picked from commit f7933241d0874f69d5c2c783f400de6cb3ff473a)
Change-Id: I732856effed160fce5cf3c47de5884e584730255