RDKCMF-8846 Update tvsettings recipes
tvsettings recipes need updating to fix build errors:

tvsettings-hal-noop:
| tvsettings-hal-noop.c:23:20: fatal error: mfrMgr.h: No such file or directory
|  #include mfrMgr.h
|                     ^
| compilation terminated.

tvsettings:
Collected errors:
 * opkg_solver_install: Cannot install package tvsettings.
...
ERROR: rdk-generic-hybrid-wpe-tdk-image-1.0-r0 do_rootfs: Function failed: do_rootfs

tvsettings-plugins:
has dependencies on jsoncpp and boost

Change-Id: I0dd6a6aad8d280b4b0cd489c5ff4f34604be0899